export const actionIcons: Record<string, string> = {
  create: "add",
  modify: "edit",
  remove: "delete",
  clear: "clear_all",
  import: "database_upload",
  export: "file_export",
  upload: "upload",
  download: "download",
  unlock: "lock_open",
  relation: "link",
  member: "group_add_outline",
  authorize: "privacy_tip_outline",
  config: "plug_connect",
  execute: "motion_play",
  enable: "check_circle",
  disable: "do_not_disturb_on",
  search: "search",
  reset: "replay",
  refresh: "refresh",
  data: "data_table",
  field: "plug_connect",
  section: "plug_connect",
  cancel: "close",
  submit: "check_circle",
  show: "undereye",
  sync: "sync",
  add: "add",
  more: "more_horiz",
  publish: "send"
};

export const pageIcons: Record<string, string> = {
  home: "home",
  system: "settings",
  groups: "account_tree",
  users: "person",
  privileges: "admin_panel_settings",
  dictionaries: "book_3",
  logs: "lab_profile",
  operationLogs: "clinical_notes",
  accessLogs: "note_alt",
  auditLogs: "list_alt",
  schedulerLogs: "event_note",
  scripts: "terminal",
  exploiters: "build",
  connections: "database_search",
  files: "folder_open",
  schemes: "genetics",
  codes: "folder_code",
  samples: "code_blocks",
  archives: "assignment_add",
  modules: "modeling",
  fragments: "code",
  reports: "assignment_add",
  regions: "location_on",
  docs: "drive_file_move",
  templates: "temple_hindu",
  messages: "business_messages",
  sent: "outgoing_mail",
  inbox: "inbox",
  schedulers: "schedule",
  tasks: "task_alt",
  audits: "safety_check",
  patrols: "person_shield"
};

export const globalIcons: Record<string, string> = {
  logout: "logout",
  help: "help",
  profile: "manage_accounts",
  translate: "translate",
  link: "link",
  desktop: "desktop_windows",
  image: "image",
  video: "videocam",
  doc: "docs",
  folder: "folder_open",
  phone: "phone_in_talk",
  email: "mail",
  person: "person",
  key: "key_vertical",
  dark: "dark_mode",
  light: "light_mode",
  ring: "notifications"
};

export const shceduleStatusIcon: { [key: string]: string } = {
  PENDING: "pending",
  RUNNING: "progress_activity",
  SUCCESS: "check",
  FAILED: "error",
  CANCELED: "cancel"
};
