export const actionIcons: Record<string, string> = {
  create: "add-rounded",
  modify: "edit-outline-rounded",
  remove: "delete-outline-rounded",
  clear: "clear-all-rounded",
  import: "database-upload-outline-rounded",
  export: "file-export-outline-rounded",
  upload: "upload-rounded",
  download: "download-rounded",
  unlock: "lock-open-outline-rounded",
  relation: "link-rounded",
  member: "group-add-outline",
  authorize: "privacy-tip-outline",
  config: "plug-connect-outline-rounded",
  execute: "motion-play-outline-rounded",
  enable: "check-circle-outline-rounded",
  disable: "do-not-disturb-on-outline-rounded",
  search: "search-rounded",
  reset: "replay-rounded",
  refresh: "refresh-rounded",
  data: "data-table-outline-rounded",
  field: "plug-connect-outline-rounded",
  section: "plug-connect-outline-rounded",
  cancel: "close-rounded",
  submit: "check-circle-outline-rounded",
  show: "undereye-rounded",
  sync: "sync-rounded",
  add: "add-rounded",
  more: "more-horiz",
  publish: "send-outline-rounded"
};

export const pageIcons: Record<string, string> = {
  home: "home-outline-rounded",
  system: "settings-outline-rounded",
  groups: "account-tree-outline-rounded",
  users: "person-outline-rounded",
  privileges: "admin-panel-settings-outline-rounded",
  roles: "shield-person-outline-rounded",
  dictionaries: "book-3-outline-rounded",
  logs: "lab-profile-outline-rounded",
  operationLogs: "clinical-notes-outline-rounded",
  accessLogs: "sticky-note-2-outline-rounded",
  auditLogs: "note-alt-outline-rounded",
  schedulerLogs: "event-note-outline-rounded",
  scripts: "terminal-rounded",
  exploiters: "build-outline-rounded",
  connections: "database-search-rounded",
  files: "folder-open-outline-rounded",
  schemes: "genetics-rounded",
  codes: "folder-code-outline-rounded",
  samples: "code-blocks-outline-rounded",
  archives: "assignment-add-outline-rounded",
  modules: "modeling-outline-rounded",
  fragments: "code-rounded",
  reports: "report-outline-rounded",
  regions: "location-on-outline-rounded",
  docs: "drive-file-move-outline-rounded",
  templates: "temple-hindu-outline-rounded",
  messages: "business-messages-outline-rounded",
  sent: "outgoing-mail-outline-rounded",
  inbox: "inbox-outline-rounded",
  schedulers: "schedule-outline-rounded",
  tasks: "task-alt-rounded"
};

export const globalIcons: Record<string, string> = {
  logout: "logout-rounded",
  help: "help-outline-rounded",
  profile: "manage-accounts-rounded",
  translate: "translate-rounded",
  link: "link-rounded",
  desktop: "desktop-windows-outline-rounded",
  image: "image-outline-rounded",
  video: "videocam-outline-rounded",
  document: "docs-outline-rounded",
  other: "devices-fold-2-outline",
  phone: "phone-in-talk-rounded",
  email: "mail-outline-rounded",
  person: "person-outline-rounded",
  key: "key-vertical-outline-rounded",
  dark: "dark-mode-outline-rounded",
  light: "light-mode-outline-rounded",
  ring: "notifications-outline-rounded"
};

export const shceduleStatusIcon: Record<string, string> = {
  PENDING: "pending-outline",
  RUNNING: "progress-activity",
  SUCCESS: "check-rounded",
  FAILED: "error-outline-rounded",
  CANCELED: "cancel-outline-rounded"
};
